json.extract! place,
              :id,
              :google_id,
              :unit_id,
              :name,
              :formatted_address,
              :state,
              :category,
              :created_at,
              :updated_at
